[package]
name = "bio_files_py"
version = "0.3.3"
edition = "2024"

[lib]
crate-type = ["cdylib"]


[dependencies]
bio_files_rs = { package = "bio_files", path = ".." }
pyo3 = { version = "0.27.1", features = ["extension-module", "abi3-py310"] }